version: 0.2

env:
  parameter-store:
    keybase_endpoint: '/keybase_endpoint'
phases:
  build:
    commands:
      - docker build -t test-image:latest .
  post_build:
    commands:
      - sleep 5
      - GROUPID=$(echo "$CODEBUILD_BUILD_ID" | cut -d ":" -f 1)
      - STREAMID=$(echo "$CODEBUILD_BUILD_ID" | cut -d ":" -f 2)
      - echo "$STREAMID"
      - EVENTS=$(aws logs get-log-events --log-group-name "/aws/codebuild/$GROUPID" --log-stream-name "$STREAMID" --output text | tail -n 80)
      - curl "$keybase_endpoint" -d '{"msg":"'"$EVENTS"'"}'
